name: Create GitHub Release

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.csproj'
      
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Install hub
      run: |
        sudo apt-get update
        sudo apt-get install hub

    - name: Extract Version from .csproj
      id: get_version
      run: |
        version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' src/DDD.Foundation/DDD.Foundation.csproj)
        echo "Package version: $version"
        echo "::set-output name=version::$version"

    - name: Generate Release Notes
      id: generate_notes
      run: |
        release_notes=$(hub pr list -s merged -L 1 -f "* %t%n")
        echo "Release Notes: $release_notes"
        echo "::set-output name=notes::$release_notes"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        body: ${{ steps.generate_notes.outputs.notes }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
