# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to NuGet Staging

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Pack
      run: dotnet pack --no-build -c Release -o out
      
    - name: Push to NuGet Staging
      run: dotnet nuget push out/*.nupkg -k ${{ secrets.NUGET_API_KEY_STAGING }} -s https://int.nugettest.org/api/v2/package
